exclude: "^.venv/.*"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.0.1"
    hooks:
    -   id: trailing-whitespace
  - repo: local
    hooks:
    - id: workflows
      name: workflows
      language: system
      entry: poetry run python .github/workflows/export.py
      types: [python]
    - id: isort
      name: isort
      language: system
      entry: poetry run isort
      types: [python]
    - id: black
      name: black
      language: system
      entry: poetry run black
      types: [python]
    - id: ruff
      name: ruff
      language: system
      entry: poetry run ruff
      types: [python]
    - id: mypy
      name: mypy
      language: system
      entry: poetry run mypy
      types: [python]
      pass_filenames: false
